packages:
  - "apps/**"
  - "packages/**"

allowBuilds:
  '@prisma/engines': true
  prisma: true
  unrs-resolver: true
  esbuild: true
  lightningcss: true
  '@embedded-postgres/linux-x64': true
  argon2: true
  protobufjs: true

minimumReleaseAge: 0
